### ISSUE TITLE
Log the URL to access the app

### ISSUE THREAD

**Issue by mrsarm** [medic/nginx-local-ip#15]
Now when the container starts it logs the value of $APP_URL like this:

    nginx-local-ip    | /entrypoint.sh: $APP_URL set to http://192.168.1.9:5988

Would be nice to see also the computed URL that the user can use to access the app, so it only needs to do copy & paste in case is going to use the the app in the same computer or needs to share it:

    nginx-local-ip    | /entrypoint.sh: New URL to access the app: https://192-168-1-9.my.local-ip.co

**Comment by mrjones-plip** [comment]
@mrsarm - I would actually leave that line as is, because it's correctly showing the value of `APP_URL`. Instead I would change the last line with maybe some fancy formatting if possible? From this:

```
nginx-local-ip    | /entrypoint.sh: Configuration complete; ready for start up
```

To this:

```
nginx-local-ip    | /entrypoint.sh: Configuration complete; ready for start up
nginx-local-ip    | /entrypoint.sh: 
                         -----------------------------
                         nginx-local-ip ready at:
                         https://192-168-1-9.my.local-ip.co
                         -----------------------------
```

That way it really pops out of the CLI!

**Comment by mrsarm** [comment]
Yes, actually I was thinking to add the log with the public URL but without removing the first one.

Definitively yes, highlight the public URL in the logs as you suggest would make easier for the user to locate it within the logs.

**Comment by mrsarm** [comment]
Worth to note though, that the line:

```
Configuration complete; ready for start up
```

Comes from the nginx docker image script, not from our script: 

https://github.com/medic/nginx-local-ip/blob/5f4af9d269d55698ffb45496c4de39540e2da73e/entrypoint.sh#L60

But we can append in our script the lines you suggest, just after the line mentioned above.

**Comment by mrsarm** [comment]
Oh you actually didn't replace the log in your example, just append, sorry :smile:
