### ISSUE TITLE
Update to use local-ip.medicmobile.org

### ISSUE THREAD

**Issue by mrjones-plip** [medic/nginx-local-ip#24]
With the [DNS issues](https://github.com/medic/cht-core/issues/8100) that have been happening with local-ip.co, we should update this project to allow the URLs of the full chain and private key to be passed in docker compose variables.  We can then have them default to use the new and more stable service local-ip.medicmobile.org, but still be backwards compatible with local-ip.co and forwards compatible with any other provider in this space.

**Comment by mrsarm** [comment]
Hey @mrjones-plip ! 

I like the idea of making the project more agnostic of the DNS provider, and checking the code, I think just removing the hardcoded URLs `CERT_PEM_SRC`, `CERT_KEY_SRC` and `CERT_CHAIN_SRC` [here](https://github.com/medic/nginx-local-ip/blob/04f4fadc70054c098055e5f35cc617105411c609/entrypoint.sh#L12-L16), and passing them through the `docker-compose.yml` file would be enough. This way, documenting in the README that you only need to change the env from the compose file or an .env file, and even providing a `docker-compose.medic.yml` with the configurations for the medic server would be enough.

Let me know if you think this is the right approach, and I would be happy to contribute back with Medic and this project a bit, creating a draft PR that we can work on together.

**Comment by mrjones-plip** [comment]
Hey @mrsarm!  Nice of you to follow this issue and extra nice of you to offer to help - thank you!

I think your approach sounds good and is exactly what I was thinking.  I would flip the logic on the compose files though: we should default to our provider and then offer a   `docker-compose.local-ip.co.yml` if folks want to use the deprecated provider.  This is a really great idea though to offer the different compose files - it not only is backwards compatible, but also shows how to put the logic of adding a new provider in a compose file. Lovely!

**Comment by mrsarm** [comment]
Sounds good! question: does local-ip.medicmobile.org provides the same features than local-ip.co ? is out there public information about it? like the one at http://local-ip.co ? because if this project is public, information about the DNS used by default should be public as well, otherwise a private fork defaulted to medic I think would be a better option.
