### ISSUE TITLE
access all parts of the device through the IP address

### ISSUE THREAD

**Issue by mrjones-plip** [medic/nginx-local-ip#28]
@Hamidzai456hzj asked:

> I want to access all parts of the device through the IP address of my mobile or to access a small part of the device so that I can get my mobile phone or get the files and photos that were in my device. can i do it ؟؟؟
can you help me? Thank you very much.

**Comment by mrjones-plip** [comment]
hi @Hamidzai456hzj !  Thanks for your question.  I moved it from the other ticket so we can better focus on your problem.

The way `nginx-local-ip` works is that it explicitly only exposes one port on your computer where you have a web server running (like [CHT Core](https://github.com/medic/cht-core)) and allows you to access that with a valid TLS certificate from a mobile device or other computer on the local network.

It sounds like you want to browse all files on either the mobile device or host computer running `nginx-local-ip`.  This is not a feature we support, sorry.  Only the use case mentioned above.  

I'm going to close the ticket, but if I've misunderstood your use case, please feel free to clarify the issue you're facing!

**Comment by yasar456uhyhluih** [comment]
IP Address
192.168.0.110
MAC Address
F6-B7-C0-87-C3-48
در باره این که این دستگاه و فایل هایش را چیگونه دوباره بدست اورم

**Comment by yasar456uhyhluih** [comment]
About finding this device and its files again

**Comment by yasar456uhyhluih** [comment]
P Address
192.168.0.110
MAC Address
F6-B7-C0-87-C3-48

About finding this device and its files again
